### ISSUE TITLE
Diagram labels

### ISSUE THREAD

**Issue by damccull** [cmdrdahkron/elite-binds#1]
Why are there 3 diagrams? What does each represent?

**Comment by RyanBreaker** [comment]
Directly under the controller is a caption, so each one seems to include specific features like while in Supercruise, while in-System (normal flight), and the last being for landing (left and right triggers become lateral thrusting rather than for weapons when the gear is down).

Admittedly not the clearest representation, but some buttons and combinations become overridden in different modes of flight.

**Comment by laurent-indermuehle** [comment]
9b4da6fab3d22343674d40c78000e7b407a6c408 should fix this. I close this issue
