### ISSUE TITLE
No controls for Buggy

### ISSUE THREAD

**Issue by cmcosta81** [cmdrdahkron/elite-binds#4]
There\s no binding for accelerator in the planet surface vehicle (dune buggy). The default uses triggers on Advanced Gamepad.

**Comment by cmdrdahkron** [comment]
Hey there, I will update this at some point - but I have a couple of other projects that are taking my attention at the moment.  I actually have a better plan for these binds ultimately, which is to create a simple tool that can merge binds into a single file rather than having to overwrite your own binds to use someone else's.  That project may or may not happen yet, so don't hold your breathe ;-)

**Comment by laurent-indermuehle** [comment]
@cmdrdahkron, do you need some help? I'm in love with those bindings, I was trying to do the same thing on my own and then I came accross this repo. You saved me tons of time.
I can code, I can test, I can edit pictures, so if you need help, I'm here :)

**Comment by cmdrdahkron** [comment]
Hey there @Honiix - I am _totally_ happy to add you as a contributor and give you access to the repo. Unfortunately I never seem to be able to get around to updating these now that I don't use a controller any more!

**Comment by laurent-indermuehle** [comment]
@cmdrdahkron thanks for the invitation. I'll do my best to contribute :)

**Comment by laurent-indermuehle** [comment]
Fixed in 9b4da6fab3d22343674d40c78000e7b407a6c408
Are you happy with the bindings?
I still don't like Vertical Thruster on B because it fires whenever you want to open a UI panel. I don't have idea for another bind for now. Any suggestions?

**Comment by laurent-indermuehle** [comment]
No complains -> Everybody seems happy then ;)
Clossing.
